name: Private Action Loader
description: Enables private Actions to be easily reused across repositories.
inputs:
  pal-repo-token:
    description: 'Access token with read access to the repo containing action'
    required: true
  pal-repo-name:
    description: 'The organization/user and repo where action is stored, with support for @ref'
    required: true
  pal-action-directory:
    description: 'The optional path to directory containing action.  Useful when multiple private actions are stored in the same repo'
    required: false
  config-file:
    description: 'The location of the branch config file'
    required: true
  repo-token:
    description: 'The github token'
    required: true
outputs:
  status-message:
    description: 'A detailed status message that can be used elsewhere (e.g. Slack)'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'lock'
  color: 'green'
